  
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  noob:
    filters: 
      branches:
          only: 
            - master
    docker:
      # specify the version
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws ec2 describe-instances
  pro:
    filters: 
      branches:
          only: 
            - master
    docker:
      # specify the version
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  plan:
    jobs:
      - noob:
          filters:
            branches:
              ignore: master
      - pro:
          filters:
            branches:
              only: master
